bazel run stubdev:cuda_fullsolve_test_4 > timing_4.txt
bazel run stubdev:cuda_fullsolve_test_7 > timing_7.txt
bazel run stubdev:cuda_fullsolve_test_10 > timing_10.txt
bazel run stubdev:cuda_fullsolve_test_11 > timing_11.txt
bazel run stubdev:cuda_fullsolve_test_12 > timing_12.txt
bazel run stubdev:cuda_fullsolve_test_13 > timing_13.txt
bazel run stubdev:cuda_fullsolve_test_14 > timing_14.txt
bazel run stubdev:cuda_fullsolve_test_15 > timing_15.txt
bazel run stubdev:cuda_fullsolve_test_22 > timing_22.txt
